#!/bin/bash
if [ -n "$TMUX" ] ; then
    # tmux session running
    # tmux split-window -h "nvim \"$*\""
    tmux split-window -h $EDITOR $1
else
    # alacritty -e "nvim \"$*\""
    alacritty -e bash -ic "$EDITOR $1" &
fi
